- hosts: localhost
  tasks:

    - name: Pull Docker Image
      command: docker pull ragh1808/scientific-calculator:latest

    - name: Stop old container
      command: docker rm -f calculator
      ignore_errors: yes

    - name: Run Container
      command: docker run -it --name calculator ragh1808/scientific-calculator:latest